INSERT IGNORE INTO users (id, username, email, password, created_at) VALUES
                                                                          (900101, 'johnDoe', 'john@example.com', '$2a$10$k307GRbFIB9IW1PcwtbjjOcQ4rLfvKIDkz5ruxOUEKteuShYRk3.2', '2025-01-01 14:27:00'),
                                                                          (900102,'janeDoe', 'jane@example.com', '$2a$10$tjy31HIaxyQz8K75TD248.61dsJbqk62a0g3mUIUkGQvNJ4B.xFi2', '2025-02-11 07:44:00'),
                                                                          (900103,'adminUser', 'admin@example.com', '$2a$10$w/Zm4PuIORcEbm545F8ypuaKSlCNMKleCwX1HYL3cJCTGjZ37sSxW', '2024-12-04 10:21:00');

INSERT IGNORE INTO posts (id, title, content, topic, user_id, created_at) VALUES
-- Java (topic_id 1)
(900201, 'Introduction à Java', 'Java est un langage de programmation orienté objet créé par James Gosling en 1995 chez Sun Microsystems. Il est connu pour son principe "Write Once, Run Anywhere" (WORA) grâce à la machine virtuelle Java (JVM) qui permet une portabilité exceptionnelle entre différentes plateformes.

Java a révolutionné le développement logiciel avec sa gestion automatique de la mémoire (garbage collection), son système de sécurité robuste et sa riche API standard. Le langage est particulièrement apprécié pour les applications d''entreprise, les systèmes Android (bien que Kotlin gagne du terrain), et les systèmes distribués.

La syntaxe de Java est inspirée de C++ mais simplifiée, éliminant notamment les pointeurs explicites et l''héritage multiple. Java introduit des concepts fondamentaux comme les interfaces, les packages, les exceptions checked/unchecked, et plus récemment les modules avec Java 9.

Avec plus de 25 ans d''existence, Java continue d''évoluer avec des versions majeures tous les six mois depuis Java 9. La communauté Java est l''une des plus vastes au monde, avec des frameworks populaires comme Spring, Hibernate, et Jakarta EE pour le développement web et d''entreprise.

Pour commencer avec Java, vous aurez besoin du JDK (Java Development Kit) qui inclut le compilateur javac et la JRE (Java Runtime Environment). Les outils comme Maven ou Gradle sont essentiels pour la gestion des dépendances dans les projets modernes.', 'JAVA', 900101, '2025-04-01 10:30:00'),
(900202, 'Les nouveautés de Java 21', 'Java 21, dernière version LTS (Long-Term Support), apporte son lot d''innovations majeures pour les développeurs. Parmi les nouveautés phares, on retrouve les patterns matching améliorés, les record patterns, ainsi que la montée en puissance des virtual threads pour faciliter la gestion de la concurrence. De nouvelles fonctionnalités incubées comme les structured concurrency viennent également enrichir l''écosystème. Java 21 confirme l''engagement d''Oracle à rendre la plateforme toujours plus moderne, performante et accessible.', 'JAVA', 900102, '2025-03-01 16:38:00'),

-- JavaScript (topic_id 2)
(900203, 'JavaScript moderne avec ES2024', 'JavaScript moderne ne se limite plus à ES6 ! Avec ES2024, le langage continue d’évoluer en apportant des fonctionnalités toujours plus puissantes et ergonomiques. Parmi les nouveautés : les méthodes toSorted, toReversed, toSpliced pour les tableaux, les améliorations des Records et Tuples, et l’optimisation du pattern matching. JavaScript moderne en 2024 combine flexibilité, simplicité et performances pour répondre aux besoins du développement web actuel.', 'JAVASCRIPT', 900103, '2025-03-14 09:04:00'),
(900204, 'Async/Await en JS', 'Avant l''arrivée d''async/await, JavaScript gérait l''asynchrone principalement avec des promesses ou des callbacks, ce qui pouvait rendre le code complexe et difficile à lire. Introduits avec ES2017, async et await permettent d''écrire du code asynchrone de manière beaucoup plus fluide, presque comme du code synchrone. Une fonction déclarée avec async retourne automatiquement une promesse, et await suspend son exécution jusqu’à ce que la promesse soit résolue. Cette approche améliore considérablement la lisibilité et la maintenabilité du code. Aujourd''hui, async/await est devenu un standard incontournable pour la gestion des appels réseau, des accès aux bases de données et de toute opération asynchrone en JavaScript.', 'JAVASCRIPT', 900101, '2025-04-01 14:35:00'),
(900205, 'Les frameworks JS en 2025', 'En 2025, les frameworks JavaScript continuent de dominer le développement web moderne avec une évolution constante. React reste un incontournable, tandis que des alternatives comme Vue.js et Svelte gagnent encore en popularité pour leur simplicité et leurs performances. Angular, toujours utilisé dans les grandes entreprises, évolue vers plus de légèreté et de modularité. De nouveaux frameworks comme SolidJS émergent également, misant sur une approche ultra-optimisée. L’accent est désormais mis sur la rapidité, l''optimisation du rendu côté client et serveur, et une meilleure expérience développeur.', 'JAVASCRIPT', 900102, '2025-03-01 22:30:00'),

-- Python (topic_id 3)
(900206, 'Pourquoi apprendre Python?', 'Apprendre Python est aujourd’hui un choix stratégique pour toute personne souhaitant se lancer dans la programmation. Grâce à sa syntaxe simple et intuitive, Python est idéal pour les débutants, tout en étant suffisamment puissant pour des projets complexes. Il est massivement utilisé dans des domaines en pleine croissance comme l''intelligence artificielle, le développement web, l''automatisation et la data science. Sa vaste communauté, ses bibliothèques riches et son accessibilité en font un langage polyvalent, recherché aussi bien dans les start-ups que dans les grandes entreprises. Python est clairement un atout pour construire une carrière technologique solide en 2025.', 'PYTHON', 900103, '2025-03-01 10:10:00'),
(900207, 'Les décorateurs en Python', 'Les décorateurs en Python sont des fonctions spéciales qui permettent de modifier ou d''enrichir le comportement d''autres fonctions ou classes sans en changer directement le code. Très utilisés dans les frameworks modernes comme Flask ou Django, ils offrent une manière élégante de factoriser et de réutiliser du code, notamment pour la gestion des permissions, la mise en cache ou la journalisation. En ajoutant simplement @decorator_name au-dessus d''une fonction, on peut y injecter de nouvelles fonctionnalités. Les décorateurs font partie des concepts avancés de Python, mais leur maîtrise est un véritable atout pour écrire du code propre, modulaire et maintenable.', 'PYTHON', 900101, '2025-04-01 11:14:00'),

-- Angular (topic_id 4)
(900208, 'Angular vs React', 'Angular et React sont deux piliers du développement web moderne, mais ils adoptent des approches différentes. Angular, développé par Google, est un framework complet proposant une structure solide et de nombreux outils intégrés dès le départ. React, développé par Meta (Facebook), est une bibliothèque plus légère et flexible, centrée sur la création d''interfaces utilisateur, souvent combinée avec d’autres librairies pour construire des applications complètes. Angular convient bien aux projets complexes et aux grandes équipes, tandis que React séduit par sa simplicité, sa rapidité d''apprentissage et sa communauté très active. Le choix dépend avant tout des besoins du projet et des préférences de l''équipe.', 'ANGULAR', 900102, '2025-02-01 15:40:00'),
(900209, 'Les Signals dans Angular 18', 'Avec Angular 18, les Signals font leur apparition pour révolutionner la gestion de l''état dans les applications. Un Signal est une source de données réactive qui permet de suivre automatiquement les changements de valeur sans avoir besoin d''observer manuellement les flux. Cette approche rend le code plus prévisible, plus performant et simplifie la détection des changements par Angular. Les Signals offrent une alternative moderne à l''utilisation massive des Observables dans certains cas, tout en restant compatibles avec l''écosystème existant. Ils marquent une étape importante vers un Angular plus réactif et plus intuitif.', 'ANGULAR', 900103, '2025-02-01 18:38:00'),

-- React (topic_id 5)
(900210, 'React Hooks expliqués', 'Les Hooks ont été introduits dans React pour simplifier la gestion de l’état et du cycle de vie dans les composants fonctionnels. Avant leur arrivée, seules les classes pouvaient utiliser l’état interne et les méthodes de cycle de vie. Avec des hooks comme useState, useEffect ou useContext, il est désormais possible de créer des composants plus courts, plus lisibles et plus modulaires. Les Hooks permettent de mieux organiser la logique métier en la séparant du rendu visuel. Ils sont devenus essentiels pour développer des applications modernes en React, en rendant le code plus propre et plus facile à maintenir.', 'REACT', 900101, '2025-03-01 18:30:00'),
(900211, 'Optimisation des performances React', 'Optimiser les performances dans React est essentiel pour offrir une expérience utilisateur fluide, surtout dans les grandes applications. Cela passe par différentes techniques comme la mémorisation des composants avec React.memo, l''optimisation des fonctions avec useCallback, ou encore la gestion intelligente des états avec useReducer. Le lazy loading des composants et le découpage du code permettent également de réduire le temps de chargement initial. En limitant les rendus inutiles et en adoptant une architecture performante, il est possible de rendre les applications React beaucoup plus rapides et réactives.', 'REACT', 900102, '2025-02-01 21:34:00'),

-- Node.js (topic_id 6)
(900212, 'Construire une API REST avec Node', 'Construire une API REST avec Node.js est une approche courante pour créer des services backend performants et légers. En combinant Node avec Express.js, un framework minimaliste, il est facile de définir des routes, gérer les requêtes HTTP et structurer des endpoints RESTful. On peut y intégrer une base de données (comme MongoDB ou PostgreSQL), des middlewares pour la sécurité (CORS, authentification), et des outils pour la validation ou la documentation (comme Swagger). Grâce à son architecture non bloquante, Node.js permet de gérer efficacement de nombreuses requêtes simultanées, ce qui en fait un excellent choix pour des API rapides et scalables.', 'NODEJS', 900103, '2025-02-01 08:32:00'),
(900213, 'Gestion des erreurs en Node.js', 'La gestion des erreurs en Node.js est essentielle pour assurer la fiabilité d''une application. Comme Node utilise une architecture asynchrone, il est crucial d''anticiper les erreurs, que ce soit dans les callbacks, les promesses ou les middlewares. L''utilisation de blocs try/catch avec async/await, combinée à des gestionnaires d''erreurs centralisés dans Express, permet de capturer et de traiter proprement les exceptions. Il est également important de ne jamais laisser une erreur non gérée, au risque de planter tout le serveur. Une bonne stratégie de gestion d’erreurs améliore la stabilité, facilite le débogage et garantit une meilleure expérience pour les utilisateurs finaux.', 'NODEJS', 900101, '2025-03-01 10:23:00'),

-- SpringBoot (topic_id 7)
(900214, 'Démarrer avec Spring Boot', 'Spring Boot est un framework Java qui simplifie la création d’applications web et d’API robustes en quelques étapes seulement. Il propose une configuration automatique intelligente, ce qui permet aux développeurs de se concentrer sur la logique métier sans perdre de temps sur le paramétrage technique. Grâce à son approche "opinionated", il suffit souvent de quelques annotations pour lancer une application complète. Spring Boot intègre également des outils puissants comme Spring Data JPA, Spring Security ou Actuator pour surveiller et sécuriser l’application. C’est aujourd''hui une solution incontournable pour développer rapidement des services professionnels en Java.', 'SPRINGBOOT', 900102, '2025-02-01 09:04:00'),
(900215, 'Spring Security en pratique', 'Spring Security est le module incontournable pour gérer l’authentification et l’autorisation dans les applications Java. En pratique, il permet de sécuriser rapidement les accès aux routes, de protéger les API REST, et d’intégrer facilement différents modes d’authentification (formulaire, JWT, OAuth2, etc.). Grâce à une configuration basée sur des filtres et des annotations (@PreAuthorize, @Secured), il est possible de contrôler finement les droits des utilisateurs. Spring Security s’adapte aussi bien aux petites applications qu’aux architectures complexes en garantissant un haut niveau de sécurité avec une grande flexibilité.', 'SPRINGBOOT', 900103, '2025-03-01 10:51:00'),

-- MySQL (topic_id 8)
(900216, 'Optimisation des requêtes MySQL', 'Optimiser les requêtes MySQL est essentiel pour garantir de bonnes performances, surtout lorsque les bases de données deviennent volumineuses. Cela passe par l’utilisation efficace des index, l''écriture de requêtes ciblées et l''évitement des opérations coûteuses comme les jointures inutiles ou les sous-requêtes mal pensées. L''analyse des requêtes avec des outils comme EXPLAIN permet d''identifier les points de blocage. La normalisation du schéma, la limitation du volume de données retournées et la mise en cache des résultats critiques contribuent également à accélérer les performances. Une bonne optimisation réduit la charge serveur et améliore l’expérience utilisateur.', 'MYSQL', 900101, '2025-04-01 10:40:00'),
(900217, 'Migration MySQL 5.7 vers 8.0', 'La migration de MySQL 5.7 vers 8.0 est une étape importante pour bénéficier des améliorations de performance, de sécurité et des nouvelles fonctionnalités du moteur. Avant de migrer, il est essentiel de vérifier la compatibilité du schéma et du code existant, car certaines fonctions et comportements ont été modifiés ou supprimés. L''utilisation de l''outil mysql_upgrade et la lecture attentive du guide de migration officiel permettent d’anticiper les problèmes. Il est aussi recommandé de tester la migration sur un environnement de préproduction. Passer à MySQL 8.0, c’est profiter d’une meilleure gestion des index, de nouvelles fonctions SQL et d’un moteur plus optimisé.', 'MYSQL', 900102, '2025-04-01 10:38:00'),

-- PostgreSQL (topic_id 9)
(900218, 'Fonctionnalités avancées de PostgreSQL', 'PostgreSQL est reconnu pour ses nombreuses fonctionnalités avancées qui en font un choix privilégié pour les applications exigeantes. Parmi elles, on retrouve la gestion native des types JSON et JSONB pour le stockage de données semi-structurées, le support des requêtes full-text pour des recherches efficaces, ainsi que les vues matérialisées pour optimiser les performances. PostgreSQL propose également des transactions complexes avec le support du MVCC (Multi-Version Concurrency Control) et permet de créer des procédures stockées en plusieurs langages. Sa flexibilité, sa robustesse et son extensibilité en font un véritable moteur de base de données de niveau entreprise.', 'POSTGRESQL', 900103, '2025-04-01 17:30:00'),
(900219, 'PostgreSQL vs MySQL', 'PostgreSQL et MySQL sont deux des bases de données relationnelles les plus populaires, mais ils répondent à des besoins différents. PostgreSQL est souvent choisi pour sa richesse fonctionnelle, son respect rigoureux des standards SQL et sa capacité à gérer des opérations complexes, notamment avec des types de données avancés et des transactions sophistiquées. MySQL, de son côté, est réputé pour sa simplicité, sa rapidité sur des charges de travail classiques et son excellente intégration avec de nombreux environnements web. Le choix entre PostgreSQL et MySQL dépend généralement du type de projet : PostgreSQL pour les applications critiques et complexes, MySQL pour les solutions légères et rapides.', 'POSTGRESQL', 900101, '2025-04-01 18:32:00'),

-- AI (topic_id 10)
(900220, 'Introduction au Machine Learning', 'Le Machine Learning (ou apprentissage automatique) est une branche de l''intelligence artificielle qui permet aux machines d''apprendre à partir de données, sans être explicitement programmées pour chaque tâche. L''idée principale est de développer des algorithmes capables de repérer des motifs, de faire des prédictions ou de prendre des décisions en s''améliorant au fil du temps. Le Machine Learning se divise en plusieurs catégories : l''apprentissage supervisé, non supervisé et par renforcement. On le retrouve aujourd''hui dans de nombreux domaines comme la reconnaissance d’images, les moteurs de recommandation, la détection de fraudes ou encore la conduite autonome. La qualité des données et le choix du bon modèle sont essentiels pour obtenir des résultats fiables. Avec la croissance exponentielle des volumes de données, le Machine Learning est devenu un levier stratégique pour les entreprises cherchant à automatiser, prédire ou mieux comprendre leur environnement.', 'AI', 900102, '2025-04-01 16:15:00'),
(900221, 'TensorFlow vs PyTorch', 'TensorFlow et PyTorch sont les deux frameworks les plus populaires pour développer des modèles de Machine Learning et d''intelligence artificielle. TensorFlow, développé par Google, est réputé pour sa robustesse en production, son écosystème très complet (avec TensorFlow Serving, TensorFlow Lite, etc.) et son support avancé pour le déploiement sur différents appareils. De son côté, PyTorch, soutenu par Meta (Facebook), séduit par sa simplicité d’utilisation, son approche plus intuitive et son mode de calcul dynamique qui facilite l’expérimentation et la recherche. Aujourd''hui, PyTorch est très prisé dans le milieu académique, tandis que TensorFlow reste dominant dans les environnements industriels. Le choix entre les deux dépend souvent du type de projet : rapidité d’expérimentation pour PyTorch, mise en production massive pour TensorFlow.', 'AI', 900103, '2025-03-01 15:48:00'),

-- ASP.NET (topic_id 11)
(900222, 'Débuter avec ASP.NET Core', 'ASP.NET Core est un framework open-source, moderne et multiplateforme développé par Microsoft pour créer des applications web, des API REST et des services cloud performants. Conçu pour être léger et modulable, il fonctionne aussi bien sous Windows que sous Linux ou macOS. Pour débuter, il suffit de créer un projet avec Visual Studio ou Visual Studio Code, et d''exploiter le système de routage, l''injection de dépendances native, et l''intégration facile avec les bases de données grâce à Entity Framework Core. ASP.NET Core permet également d''ajouter très simplement des fonctionnalités de sécurité, d''authentification et de gestion d''erreurs. Grâce à son architecture orientée performance et extensibilité, il est idéal pour développer des applications modernes et évolutives.', 'ASPNET', 900101, '2025-04-01 16:44:00'),
(900223, 'Authentification dans ASP.NET', 'L’authentification dans ASP.NET est un élément clé pour sécuriser les applications web et les API. ASP.NET Core propose plusieurs méthodes d''authentification prêtes à l''emploi : authentification par cookie, authentification basée sur JWT (JSON Web Tokens) pour les API, ou encore intégration avec des fournisseurs externes comme Google, Microsoft ou Facebook via OAuth2/OpenID Connect. Grâce au système d''injection de dépendances et aux middleware d’authentification (UseAuthentication, UseAuthorization), il est facile de configurer et de protéger des routes spécifiques. Le framework propose aussi des outils comme Identity pour gérer facilement les utilisateurs, les rôles et les politiques d''accès. Bien maîtriser l’authentification permet de construire des applications sûres, évolutives et adaptées aux standards de sécurité modernes.', 'ASPNET', 900102, '2025-03-01 14:52:00'),

-- CSS (topic_id 12)
(900224, 'CSS Grid vs Flexbox', 'CSS Grid et Flexbox sont deux puissants systèmes de mise en page utilisés pour construire des interfaces modernes en CSS. Flexbox est idéal pour organiser les éléments sur un seul axe (horizontal ou vertical) et offre une grande souplesse pour aligner, répartir et ordonner les éléments dans un conteneur. CSS Grid, en revanche, est conçu pour créer des mises en page plus complexes en deux dimensions (lignes et colonnes) avec un contrôle précis sur le placement des éléments. Tandis que Flexbox excelle pour les composants internes (menus, cartes, barres d’outils), Grid est parfait pour structurer des pages entières. En pratique, les deux techniques sont souvent combinées pour tirer parti de leurs forces respectives et créer des designs web réactifs et harmonieux.', 'CSS', 900103, '2025-04-21 18:30:00'),
(900225, 'Les animations CSS modernes', 'Les animations CSS modernes permettent de créer des interfaces web dynamiques et engageantes sans avoir besoin de JavaScript. Grâce aux propriétés transition et animation, il est possible d’animer des éléments sur des changements de style (couleur, taille, position, etc.) de manière fluide. Les animations basées sur @keyframes offrent encore plus de contrôle, permettant de définir des séquences complexes. Aujourd''hui, les tendances modernes misent sur des animations légères, naturelles et respectueuses des performances, notamment grâce à des propriétés comme transform et opacity, qui sont mieux optimisées par les navigateurs. Bien utilisées, les animations améliorent l’expérience utilisateur en rendant les interactions plus intuitives et agréables.', 'CSS', 900101, '2025-02-24 01:08:00'),

-- PHP (topic_id 13)
(900226, 'PHP 8.4: Les nouveautés', 'PHP 8.4 continue d''améliorer le langage en apportant des fonctionnalités destinées à simplifier le développement et renforcer la performance. Parmi les nouveautés notables, on retrouve l’introduction des Autocapture Lambdas, qui permettent aux fonctions anonymes de capturer automatiquement les variables nécessaires. Des améliorations ont aussi été apportées aux types, avec plus de flexibilité dans les annotations et les contrôles. Côté performance, le moteur Zend bénéficie d''optimisations supplémentaires, réduisant encore la consommation mémoire et le temps d''exécution. PHP 8.4 poursuit également l''évolution amorcée dans les versions précédentes vers un langage plus moderne, strict et orienté vers les bonnes pratiques de programmation.', 'PHP', 900102, '2025-04-09 10:17:00'),
(900227, 'Laravel: Le framework PHP moderne', 'Laravel est aujourd''hui le framework PHP le plus populaire pour développer des applications web modernes et robustes. Connu pour sa syntaxe élégante et expressive, il facilite le développement grâce à de puissants outils intégrés : système de routage, ORM Eloquent pour manipuler les bases de données, gestion d’authentification et système de migration de schéma. Laravel met aussi l''accent sur la productivité avec des outils comme Artisan (interface en ligne de commande) et Laravel Breeze ou Jetstream pour le scaffolding rapide d''applications. Sa structure modulaire, son écosystème riche (avec Laravel Forge, Vapor, Nova) et son respect des bonnes pratiques font de Laravel un choix incontournable pour tout projet PHP moderne.', 'PHP', 900103, '2025-03-24 10:22:00'),

-- Rust (topic_id 14)
(900228, 'Pourquoi Rust gagne en popularité?', 'Rust connaît une montée en popularité impressionnante grâce à son approche unique alliant performance, sécurité et modernité. Conçu pour éviter les erreurs courantes de gestion mémoire sans sacrifier la vitesse d’exécution, Rust offre une alternative solide aux langages traditionnels comme C ou C++. Son système de possession (ownership) et d''emprunt (borrowing) garantit la sécurité mémoire à la compilation, sans besoin de garbage collector. Rust séduit aussi par son excellent écosystème (avec Cargo pour la gestion des paquets) et sa documentation exemplaire. Aujourd''hui, il est de plus en plus utilisé dans des domaines critiques comme les systèmes embarqués, la blockchain, ou encore le développement d''applications web performantes avec des outils comme WebAssembly.', 'RUST', 900101, '2025-04-11 12:47:00'),
(900229, 'Rust pour le web: Actix vs Rocket', 'Rust n’est pas seulement réservé aux systèmes bas niveau : il s''impose aussi peu à peu dans le développement web grâce à des frameworks performants comme Actix et Rocket. Actix est reconnu pour sa rapidité exceptionnelle et son approche basée sur un système d''acteurs, parfait pour construire des API ultra-performantes. Il est particulièrement adapté aux applications nécessitant une forte montée en charge. Rocket, de son côté, mise sur la simplicité et la facilité de développement avec une syntaxe ergonomique et intuitive, idéale pour prototyper rapidement des applications web. Tandis qu''Actix privilégie la performance brute, Rocket séduit par son confort d''utilisation. Le choix dépendra donc du projet : efficacité maximale avec Actix, développement plus fluide avec Rocket.', 'RUST', 900102, '2025-02-28 17:38:00');

INSERT IGNORE INTO comments (id, content, user_id, post_id, created_at) VALUES
-- Commentaires sur Java
(900301, 'Excellent article sur Java ! Juste une précision : le WORA (Write Once Run Anywhere) est effectivement un des grands atouts de Java, mais il faut quand même faire attention aux différences entre les JVM sur certaines plateformes.', 900102, 900201, '2025-04-02 09:15:00'),
(900302, 'Java 21 est une vraie révolution avec les virtual threads. On a fait des tests en prod et le gain de performance est impressionnant pour les applications concurrentes !', 900103, 900202, '2025-03-02 14:22:00'),
(900303, 'Petit conseil pour les débutants : bien maîtriser les streams et Optional avant de se lancer dans les nouvelles features de Java 21.', 900101, 900201, '2025-04-03 11:05:00'),

-- Commentaires sur Angular
(900304, 'Angular 18 avec les Signals change vraiment la donne. Plus besoin de se battre avec les Observables pour des cas simples !', 900101, 900209, '2025-02-02 10:30:00'),
(900305, 'Le débat Angular vs React est sans fin... Perso je préfère Angular pour les gros projets d''entreprise, la structure est plus claire.', 900103, 900208, '2025-02-03 16:45:00'),
(900306, 'Attention avec les Signals, c''est puissant mais il ne faut pas abandonner RxJS pour autant. Les deux ont leurs cas d''usage !', 900102, 900209, '2025-02-05 08:12:00'),

-- Commentaires sur JavaScript
(900307, 'Async/await a sauvé ma vie ! Plus besoin de "callback hell" ou de chaînes de .then() à n''en plus finir.', 900103, 900204, '2025-04-02 15:20:00'),
(900308, 'ES2024 apporte enfin des méthodes immuables pour les tableaux (toSorted etc.), ça va simplifier beaucoup de code !', 900101, 900203, '2025-03-15 12:30:00'),
(900309, 'Pour les frameworks JS en 2025, je rajouterais Qwik dans la liste des nouveaux venus prometteurs !', 900102, 900205, '2025-03-03 09:45:00'),
(900310, 'Petit piège avec async/await : n''oubliez pas le try/catch sinon les erreurs peuvent passer silencieusement...', 900103, 900204, '2025-04-03 17:10:00');